### ISSUE TITLE
Remove lodash dependency?

### ISSUE THREAD

**Issue by donmccurdy** [graphiq/TagSelect.js#2]
Hey there!

What's your JS compilation and browser support look like these days? If I submit a PR removing the lodash dependency, since ES5 is pretty universal and easy to polyfill anyway, could that be merged here without breaking anything?

**Comment by cgoldberg17** [comment]
DON MCCURDY

**Comment by schnerd** [comment]
Greetings!

Our browser support is >= IE9 today, we use Babel for Graphiq Search and one or two other small parts of the platform, but other than that no JS compilation (only minification). We generally use Selectize or React-Select these days, I just checked and we only use TagSelect in 3 places and none of them are user-facing, which largely makes browser compatibility & minor bloat a non-issue. I think if this is going to exist as an open source project it makes sense to remove the global lodash dependency. There are two ways we could approach this:

A. We can transfer ownership of the repo to you. I think you might be a better maintainer since we only use this in a handful of places, and have largely settled on a couple of alternatives.
B. You can submit a pull request here. If the changes end up being more substantial, we'll just make a private fork internally and continue using that.

@dylanwenzlau @alexwilson2012 any thoughts?

**Comment by dylanwenzlau** [comment]
Hi Don!

Seems reasonable to let Don be the core maintainer, since he's the only one who has written code in the repo, and since we don't heavily rely on it. There are 3 ways of doing that I think - 1) give Don write access to the main repo, 2) give Don the main repo and then fork it ourselves, 3) have Don fork the repo and treat that his fork as the new main repo.

#1 might be limiting in our current submodule setup, since we'll have to delicately fine-tune which revision we're on, since master might contain new backward-incompatible changes that open-source contributors cannot go into our codebase and update. I think #2 or #3 would give open source contributors the most freedom.

**Comment by alexwilson2012** [comment]
Could option #4 be convincing Don to come back to Graphiq, or maybe just visit for a few days?

I would vote to make Don owner of the repo and we would just continue using it as a submodule. We would have to manually update the submodule on our end if he makes a change since submodules just point to a specific SHA1. I think thats totally fine especially since we only use it internally and have alternative solutions for anything user facing that needs more cross browser support. If in the future have to fork we can figure it out then, but considering that Don has been the only contributor to this repo and it hasn't changed in a year I'm pretty confident it won't be an issue for us.

**Comment by dylanwenzlau** [comment]
<3 option 4

**Comment by donmccurdy** [comment]
Oh hey everybody 😃 

I don't care especially who owns the repo: happy to do PRs, own it, or just have write access (← bonus here i get a cute little Graphiq badge on github? I'll take my swag where I can get it.). If your submodule is pointed to a SHA1 there's nothing I could do to break it short of a `push -f` right? And presumably you wouldn't need the updates anyway.

I don't have major changes planned, but someone pointed out there still aren't any great dependency-free tag inputs, so I thought I'd drop the `_.map()` and `_.forEach()` requirements here. And, actually, this input didn't support IE9 to begin with since it was for internal use.

Anyway. I was hoping I could visit in February but it didn't work out. Still hoping to, I should do that. ❤️

**Comment by schnerd** [comment]
React with a ❤️ emoji if you think we should transfer repo ownership and then fork it ourselves
React with a 🎉 emoji if you think we should keep the repo and add Don to the org with push access

**Comment by schnerd** [comment]
@donmccurdy Added!

**Comment by donmccurdy** [comment]
Woo! Cool thanks. :)

**Comment by donmccurdy** [comment]
Follow up – does the submodule use `dist/*`, or the source files? Wondering if anything would break using gulp/webpack like some of the other Graphiq packages.

**Comment by dylanwenzlau** [comment]
It uses source files for JS currently, dist for CSS. I think we generally use source files for our libraries, since it makes debugging simpler and it gives our own minifier (closure) the first shot at compiling the javascript. Already-minified js files are skipped by our minification process I believe.

**Comment by donmccurdy** [comment]
Ok sounds good, no webpack then.

**Comment by jdalton** [comment]
lodash is modular so you can require the non-trivial methods without including the entire lib.

**Comment by donmccurdy** [comment]
@jdalton thanks, the modularity is much appreciated!

@dylanwenzlau assuming you all decide to update this package post-updates, would you want to include an unminified (but concatenated) `dist/tagselect.lite.js` file, instead of the two files independently? My thought would be:

* `dist/tagselect.js`: Standalone file, including any lodash modules needed.
* `dist/tagselect.min.js`: Same, but minified.
* `dist/tagselect.lite.js`: Concatenated file with everything required *except* lodash.
* `dist/tagselect.lite.min.js`: Same, but minified.

**Comment by dylanwenzlau** [comment]
should work fine from our end either way. having the whole plugin (except lodash) in a single file would be convenient though.

**Comment by jdalton** [comment]
For the Lodash modules there's now [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin).

![](https://cloud.githubusercontent.com/assets/4303/15064867/2c5420b0-130e-11e6-8293-5037d359851f.gif)
